language: bash
services: docker

env:
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.7 VARIANT=apache
  - VERSION=2.6 VARIANT=apache
  - VERSION=2.6 VARIANT=apache
  - VERSION=2.6 VARIANT=apache

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - slash='/'; image="itop:$VERSION-${VARIANT//$slash/-}"

script:
  - travis_retry docker build -t "$image" .
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
